version: '3.8'

services:
  appcourse:
    build:
      context: .
    command: bash start-dev.sh
    ports:
      - "8082:8082"
      - "5006:5005"
    environment:
      GRADLE_USER_HOME: /box
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - .:/course
      - boxcourse:/box
    depends_on:
      - dbcourse
    networks:
      - ead-microservices-net
  dbcourse:
    image: postgres:14.5
    environment:
      POSTGRES_USER: ead-course
      POSTGRES_PASSWORD: ead-course
      POSTGRES_DB: ead-course
    ports:
      - "5433:5432"
    networks:
      - ead-microservices-net
  boxcourse:
    image: busybox
    volumes:
      - /box
    networks:
      - ead-microservices-net
networks:
  ead-microservices-net:
    name: ead-microservices-net
    external: true
volumes:
  dbcourse:
  boxcourse: