server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://db/ead-course
    username: ead-course
    password: ead-course

  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql