server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://dbcourse/ead-course
    username: ead-course
    password: ead-course

  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        lob:
        non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true
  output:
    ansi:
      enabled: Always

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

logging:
  level:
    com.ead:  TRACE
    root: INFO
    org.springframework.web:  DEBUG
    org.hibernate:  INFO

ead:
  api:
    url:
      auth-user: 'http://appauth:8087'