spring:
  devtools:
    remote:
      secret: 123
    restart:
      trigger-file: trigger.txt

logging:
  level:
    com.ead:  TRACE
    root: INFO
    org.springframework.web:  DEBUG
    org.hibernate:  INFO